services:
  duckfolio:
    image: ghcr.io/yorlg/duckfolio:latest
    container_name: duckfolio
    restart: unless-stopped
    ports:
      - 8080:3000
    volumes:
      - ./platform-config.json:/app/public/platform-config.json:ro
